### ISSUE TITLE
Preparation for 1.8.0 release

### ISSUE THREAD

**Issue by paulsputer** [gitblit/gitblit#1043]
These are the additional issues to resolve for inclusion in the 1.8.0 release:

- [x] #882 - Honour disable ticket repository setting
- [x] #1028 - Filestore items not paging
- [x] #1042 - Intrusive  Filestore lozenge
- [x] #962 - Patchset Delete Functionality
- [x] #1048 - Ticket References, from tickets and commits on other branches
- [x] #964 - Session loss redirects to start page
- [x] #966 - Always searching all repositories
- [x] #1061 - Filestore Listing SortBy most recent
- [x] #1062  - Document editor improved tablet support

**Comment by bviktor** [comment]
Does this mean there'll be no 1.7.2?

**Comment by gitblit** [comment]
Correct.  Paul has merged some great changes that warrant a bump.

**Comment by bviktor** [comment]
Nice, thanks for the info.

**Comment by bviktor** [comment]
And the contributions as well, of course.

**Comment by gilbertoca** [comment]
So, for projects using 1.6.2, the first step is update to 1.7 and then 1.8?

**Comment by 0x084E** [comment]
I know this is only my point of view, but it would be really nice if #964 and #966 could be fixed as well before the new release. While #964 is just annoying #966 makes the search kind of useless.
Anyway, thanks for your effort, looking forward to have the new features!

**Comment by paulsputer** [comment]
@gilbertoca I'm not aware of anything preventing you from upgrading directly from 1.6.2 to 1.8 once released.  You'll probably want to review the configuration files as there is now a separate file containing the defaults.

@0x084E I agree it would be nice to get those fixed.  PRs welcome ;)  Perhaps @mrjoel has some ideas about #964 I noticed some changes for authentication in #980 so not sure if that may have some unintended side effects.  #966 looks as though it may have been introduced with #935.

**Comment by mrjoel** [comment]
#964 is likely not as result of #980, however it may be a side-effect related to #908 which switched authentication from per-session to per-request. I'll take a further look today.

**Comment by bviktor** [comment]
Thanks in advance for everyone involved.

**Comment by ubala** [comment]
It would be good idea to include pull request #1063 in this release, since it is security related and has solution to fix it.

**Comment by paulsputer** [comment]
Hi @ubala I would like to merge it in but as mentioned in #1067  it needs further work to make it a security improvement.

**Comment by gilbertoca** [comment]
@gitblit In the interim, I've updated our server to version 1.7.1. But got [Unknown SSL protocol error in connection to](https://groups.google.com/forum/#!topic/gitblit/-CRp8KPo94A). 
Do you think it is a OS issue?

**Comment by acoberlin** [comment]
Thanks for the information. Any idea on how to integrate other Avatar Servers (like I proposed) in tests, so it can be released with 1.8.x maybe? See my comment in #816

**Comment by monkiki** [comment]
Any progress in the release?

**Comment by paulsputer** [comment]
Ok @gitblit looks like we're ready for the 1.8.0 release

**Comment by monkiki** [comment]
Great :)

**Comment by gitblit** [comment]
@paulsputer What do you think about #1081 ?

**Comment by paulsputer** [comment]
Haven't had much chance to review that one I'm afraid and probably won't get chance for at least a week or two.  Healthy quantity of changes, will probably need some additional consideration and I'd certainly want to understand any impact on LDAP.

I'm not overly keen on its config option `allowMultipleDomainAuthentication` as I would expect it to operate seamlessly, perhaps using a hash of user+domain as an internal uid for the user would solve many difficulties. 

In the interests of time and stability It may be best to integrate in a later version when we can consider the impacts and necessary changes to the UserModel.

**Comment by gitblit** [comment]
Good, I agree.  I'm not a fan of the proposed multiple domain authentication, either.

**Comment by gitblit** [comment]
Released. :tada:

Thanks for the heavy lifting @paulsputer !

**Comment by 0x084E** [comment]
@gitblit @paulsputer thanks guys, installing right now!

**Comment by bviktor** [comment]
Guys, thanks to you all! Just upgraded.

**Comment by valucn** [comment]
推荐中国网友使用中国头像服务，地址：https://www.cnavatar.com
